<?php

/*
 * Created by tpay.com
 */
use tpayLibs\src\_class_tpay\Utilities\Lang;
?>
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
  new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-K6DM955');</script>
<!-- End Google Tag Manager -->
<script type="text/javascript">
  function redirect() {
    setTimeout(function(){
      document.getElementById('tpay-payment').submit();
    }, 1000);
  }
</script>
<body onload="redirect()">
  <!-- Google Tag Manager (noscript) -->
  <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-K6DM955"
    height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <!-- End Google Tag Manager (noscript) -->
    <form id="tpay-payment" class="tpay-form" action="<?php echo $data['action_url'] ?>" method="POST"
      accept-charset="UTF-8">
      <?php foreach ($data['fields'] as $name => $value) { ?>
        <input <?php if ($name === 'kanal') {
          echo ' id="tpay-channel-input" ';
        }
        if ($name === 'akceptuje_regulamin') {
          echo ' id="tpay-regulations-input" ';
        } ?> type="hidden"
        name="<?php echo $name ?>"
        value="<?php echo $value ?>">
        <?php
      }
      ?>
      <input class="button" style="display:none"
      id="tpay-payment-submit" type="submit" value="<?php Lang::l('pay') ?>">
    </form>
  </body>
